permalink: /:year/:month/:day/:title
auto: true
pygments: true
paginate: 5
lsi: false

destination: ./local_site/

markdown: kramdown
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  coderay:
    coderay_wrap: div
    coderay_line_numbers: block
    coderay_line_numbers_start: 4
    coderay_tab_width: 2
    coderay_bold_every: 10
    coderay_css: style
